### PR TITLE
fail gracefully on signed tx in /dry-run

### LINKED ISSUE #4286: Dry-run endpoint fails with 500 code if provided a signed tx
## Expected Behavior

Return 200 code with invalid-tx error or dry-run the signed payload with/without signature check.

## Steps to Reproduce the Problem

```
$ curl -i -d '{"txs":[{ "tx": "tx_+KwLAfhCuEAuz3eUu0yWG6nX7vLGouHrTSeHl2hRPiiGL14sYrActtbIVNcgAyJhZTrnnMmclSawI6eQ3aHYawAoPg47c/EKuGT4YiACoQGmQxK4ui+7sBuUUeLWMyc4dO9Dt74sosOmlE7Lxk1O0QKkejNGUkNOQjVRc2VOcmhCNTNnUGI3dEpYaFMzSTE1LmNoYWluhxPewTsOgz2HAca/UmNAAIYPdh72EAAAzf+a3Q==" }]}' -H "Content-Type: application/json" -X POST https://testnet.aeternity.io/v3/dry-run
HTTP/2 500 
content-type: application/json
content-length: 34
date: Wed, 06 Mar 2024 06:04:52 GMT
server: Cowboy
x-cache: Error from cloudfront
via: 1.1 dc26753f88afedafee0ba98f34e1d4de.cloudfront.net (CloudFront)
x-amz-cf-pop: HAN50-P2
x-amz-cf-id: l4orzTXtgCnIFGFM5BemYtLITvi2cH8b8iOwXRSwABu5Ya1WKQH1oA==

{"reason":"Internal server error"}%
```
unsigned transaction works fine
```
$ curl -i -d '{"txs":[{ "tx": "tx_+GIgAqEBpkMSuLovu7AblFHi1jMnOHTvQ7e+LKLDppROy8ZNTtECpHozRlJDTkI1UXNlTnJoQjUzZ1BiN3RKWGhTM0kxNS5jaGFpbocT3sE7DoM9hwHGv1JjQACGD3Ye9hAAAA9dwlg=" }]}' -H "Content-Type: application/json" -X POST https://testnet.aeternity.io/v3/dry-run
HTTP/2 200 
content-type: application/json
content-length: 118
date: Wed, 06 Mar 2024 06:04:42 GMT
server: Cowboy
x-cache: Miss from cloudfront
via: 1.1 b6f98069628a983b1918e1171c5324cc.cloudfront.net (CloudFront)
x-amz-cf-pop: HAN50-P2
x-amz-cf-id: sJvdRR2mKN9Zt4pMJltnB-3NRlLOIZxqhMlRSgAUEt3AxL3ldlySiw==

{"results":[{"reason":"Internal error:\n  tx_nonce_already_used_for_account\n","result":"error","type":"name_claim"}]}%                                   
```

## Specifications

  - Node Version: 6.12.0

### PR DESCRIPTION
**Pull request by ThomasArts**
fixes #4286 

If any of the provided transactions in dry-run has wrong format, we fail with a 400 instead of 500.

dry-run transactions shall not be signed, which is now also documented in the OpenAPI spec.

This PR is supported by Æternity Foundation

### CODE REVIEW

File: apps/aehttp/src/aehttp_helpers.erl [hunk 1]
```diff
@@ -710,19 +710,29 @@ dry_run_accounts_([Account | Accounts], Acc) ->
...
         {ok, DTx} ->
             Tx = aetx:deserialize_from_binary(DTx),
             {Type, _} = aetx:specialize_type(Tx),
             case not lists:member(Type, [paying_for_tx, offchain_tx, ga_meta_tx]) of
-                true  -> dry_run_txs_(Txs, [{tx, Tx} | Acc]);
+                true  -> {ok, Tx};
                 false -> {error, lists:concat(["Unsupported transaction type ", Type])}
             end;
-        Err = {error, _Reason} ->
+         Err = {error, _Reason} ->
```
Comment (hanssv) [inline apps/aehttp/src/aehttp_helpers.erl:732]:
```suggestion
        Err = {error, _Reason} ->
```

**Review by hanssv — DISMISSED** [review]

**Review by hanssv — APPROVED** [review]

**Review by mitchelli — APPROVED** [review]
