### PR TITLE
SC WS: Fix wrong ABI error message

### LINKED ISSUE #3249: SC: WebSocket API crashes when wrong ABI is used
When a WebSocket client calls a contract with the wrong ABI version, the call fails and it sends
```
{"channel_id":"ch_2hSRxVW6GKKuKTgLCMGhYHgFD5w8TsR83LiTUk7LDgEcLyMDas","error":{"code":-32603,"message":"Internal error","request":{"jsonrpc":"2.0","method":"channels.update.call_contract","params":{"abi_version":1,"amount":1000,"call_data":"cb_KxF+ZORSGxVoZWFkc4dQ8/Q=","contract_id":"ct_2FanvyjRTDvthnZVWQzJyUJVdw3F2E2AksUZjQ2AL7bt4KxzoZ"}}},"id":null,"jsonrpc":"2.0","version":1}"
```

In the logs we have

```
2020-04-29 09:59:37.628 [debug] <0.4348.0>@aesc_fsm:handle_call_:4523 CAUGHT wrong_abi_version
2020-04-29 09:59:37.628 [debug] <0.4345.0>@sc_ws_api_jsonrpc:json_rpc_error_object:193 Unrecognized error reason: wrong_abi_version
```

The FSM is safe but yet we should return something more meaningful.

### PR DESCRIPTION
**Pull request by velzevur**
Fixes #3249

### CODE REVIEW

File: apps/aehttp/src/sc_ws_api_jsonrpc.erl [hunk 1]
```diff
@@ -178,13 +178,16 @@ json_rpc_error_object(invalid_pubkeys      , R) -> error_obj(3, [1003], R);
...
+json_rpc_error_object(wrong_vm_version     , R) -> error_obj(3, [1010], R);
 json_rpc_error_object(participant_not_found, R) -> error_obj(3, [1011], R);
 json_rpc_error_object(not_offchain_tx      , R) -> error_obj(2, [1012], R);
 json_rpc_error_object(already_onchain      , R) -> error_obj(3, [1013], R);
 json_rpc_error_object({meta, invalid}      , R) -> error_obj(3, [1014], R);
 json_rpc_error_object(invalid_fsm_id       , R) -> error_obj(3, [1016], R);
 json_rpc_error_object(bad_signature        , R) -> error_obj(3, [1017], R);
 json_rpc_error_object(not_allowed_now      , R) -> error_obj(3, [1018], R);
+json_rpc_error_object(wrong_abi_version    , R) -> error_obj(3, [1019], R);
+json_rpc_error_object(wrong_vm_version     , R) -> error_obj(3, [1020], R);
```
Comment (uwiger) [inline apps/aehttp/src/sc_ws_api_jsonrpc.erl:190]: Why two clauses for `wrong_vm_version`?

Comment (velzevur) [reply apps/aehttp/src/sc_ws_api_jsonrpc.erl:190]: First one (with code 1010) is a bug/typo

Comment (velzevur) [reply apps/aehttp/src/sc_ws_api_jsonrpc.erl:189]: Addressed
