### PR TITLE
Use safe mining setup during integration tests

### LINKED ISSUE #2928: aehttp_contracts_SUITE ==> aevm.identity_contract: FAILED badmatch keyblock
## Expected Behavior

Tests pass.

## Actual Behavior

```
----------------------------------------------------
2019-10-22 06:26:12.619
Init return #{<<"caller_id">> =>
                  <<"ak_jsmzzefzC1KbixJaw8HsHN8eQSJ4cir8Uoov8R4AgDMwb4QvL">>,
              <<"caller_nonce">> => 1,
              <<"contract_id">> =>
                  <<"ct_SdMAXaxrwLXuRtdTnUAFmqSUSjaKx93wgN8rWNSS3xC5Y7QfL">>,
              <<"gas_price">> => 1000000000,<<"gas_used">> => 193,
              <<"height">> => 4,<<"log">> => [],<<"return_type">> => <<"ok">>,
              <<"return_value">> => <<"cb_Xfbg4g==">>}



%%% aehttp_contracts_SUITE ==> aevm.identity_contract: FAILED
%%% aehttp_contracts_SUITE ==> {{badmatch,[{key_block,{key_header,6,
                                   <<104,137,7,173,139,13,29,121,101,123,78,
                                     165,187,63,15,205,29,83,89,114,18,77,15,
                                     222,91,62,138,168,24,248,42,147>>,
                                   <<104,137,7,173,139,13,29,121,101,123,78,
                                     165,187,63,15,205,29,83,89,114,18,77,15,
                                     222,91,62,138,168,24,248,42,147>>,
                                   <<151,59,194,18,115,242,160,85,126,109,26,
                                     196,97,193,248,65,68,165,6,155,241,241,63,
                                     11,117,105,255,184,145,122,55,109>>,
                                   553713663,2137769617508173514,
                                   1571725572588,5,
                                   [1337],
                                   <<182,146,13,9,59,54,36,40,161,174,207,254,
                                     2,234,157,221,60,169,3,148,178,230,221,
                                     104,177,183,85,224,225,156,245,253>>,
                                   <<217,202,108,173,192,99,13,10,129,124,71,
                                     86,232,121,148,177,243,254,160,88,174,204,
                                     22,114,15,42,51,71,75,19,135,16>>,
                                   <<0,0,0,2>>}}]},
 [{aecore_suite_utils,mine_blocks_until_txs_on_chain,5,
                      [{file,"/home/builder/aeternity/apps/aecore/test/aecore_suite_utils.erl"},
                       {line,327}]},
  {aehttp_contracts_SUITE,force_fun_calls,2,
                          [{file,"/home/builder/aeternity/apps/aehttp/test/aehttp_contracts_SUITE.erl"},
                           {line,1346}]},
  {aehttp_contracts_SUITE,identity_contract,1,
                          [{file,"/home/builder/aeternity/apps/aehttp/test/aehttp_contracts_SUITE.erl"},
                           {line,202}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1754}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1263}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1195}]}]}
```

## Steps to Reproduce the Problem

Can't be reproduced reliably atm.

## Logs, error output, etc.

https://circleci.com/gh/aeternity/aeternity/92911#tests/containers/2

Same error different test https://circleci.com/gh/aeternity/aeternity/94993#tests/containers/1

### LINKED ISSUE #2929: aehttp_sc_SUITE ==> plain.changeable_fee.sc_ws_set_fee_settle: FAILED badmatch key_block
## Expected Behavior

Tests pass.

## Actual Behavior

```
%%% aehttp_sc_SUITE ==> plain.changeable_fee.sc_ws_set_fee_settle: FAILED
%%% aehttp_sc_SUITE ==> {{badmatch,[{key_block,{key_header,482,
                                   <<107,87,196,173,134,89,89,89,101,117,53,69,
                                     76,70,97,174,245,145,131,231,61,224,178,
                                     210,174,91,115,44,187,180,239,7>>,
                                   <<107,87,196,173,134,89,89,89,101,117,53,69,
                                     76,70,97,174,245,145,131,231,61,224,178,
                                     210,174,91,115,44,187,180,239,7>>,
                                   <<150,188,103,61,128,31,44,75,103,7,76,2,
                                     212,194,134,78,73,130,15,116,171,197,71,
                                     208,236,201,66,254,98,221,101,208>>,
                                   536974990,12487735281691472059,
                                   1571725462566,5,
                                   [1337],
                                   <<203,249,48,45,139,185,78,191,151,69,62,
                                     178,79,53,83,255,188,8,10,49,47,249,42,
                                     161,206,145,221,123,195,41,27,87>>,
                                   <<217,202,108,173,192,99,13,10,129,124,71,
                                     86,232,121,148,177,243,254,160,88,174,204,
                                     22,114,15,42,51,71,75,19,135,16>>,
                                   <<0,0,0,2>>}}]},
 [{aecore_suite_utils,mine_blocks_until_txs_on_chain,5,
                      [{file,"/home/builder/aeternity/apps/aecore/test/aecore_suite_utils.erl"},
                       {line,327}]},
  {aehttp_sc_SUITE,wait_for_tx_hash_on_chain,1,
                   [{file,"/home/builder/aeternity/apps/aehttp/test/aehttp_sc_SUITE.erl"},
                    {line,2561}]},
  {aehttp_sc_SUITE,settle_,3,
                   [{file,"/home/builder/aeternity/apps/aehttp/test/aehttp_sc_SUITE.erl"},
                    {line,1215}]},
  {aehttp_sc_SUITE,'-sc_ws_set_fee_settle/1-fun-0-',2,
                   [{file,"/home/builder/aeternity/apps/aehttp/test/aehttp_sc_SUITE.erl"},
                    {line,4375}]},
  {aehttp_sc_SUITE,sc_ws_set_fee_settle,1,
                   [{file,"/home/builder/aeternity/apps/aehttp/test/aehttp_sc_SUITE.erl"},
                    {line,4380}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1546}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1062}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,994}]}]}
```
## Steps to Reproduce the Problem

Can't be reproduced reliably atm.

## Logs, error output, etc.

https://circleci.com/gh/aeternity/aeternity/92920#tests/containers/2

### LINKED ISSUE #2949: aesc_fsm_SUITE ==> all_tests.transactions.init_per_group: FAILED badmatch key_block
## Expected Behavior

Tests pass.

## Actual Behavior

```
%%% aesc_fsm_SUITE ==> all_tests.transactions.init_per_group: FAILED
%%% aesc_fsm_SUITE ==> {{badmatch,
     [{key_block,
          {key_header,69,
              <<59,35,146,6,189,54,180,44,98,2,226,91,182,241,58,240,101,146,
                246,96,140,254,70,8,30,240,150,234,246,36,142,183>>,
              <<59,35,146,6,189,54,180,44,98,2,226,91,182,241,58,240,101,146,
                246,96,140,254,70,8,30,240,150,234,246,36,142,183>>,
              <<70,74,67,196,17,33,79,3,141,142,96,152,222,103,84,230,19,156,
                125,18,25,73,226,22,244,105,87,20,177,97,140,139>>,
              543009913,14909785248260204015,1572253300840,1,
              [1337],
              <<59,79,84,89,102,202,77,36,119,180,199,158,96,210,21,59,7,95,
                186,148,188,79,104,112,118,240,234,119,145,71,197,142>>,
              <<217,202,108,173,192,99,13,10,129,124,71,86,232,121,148,177,243,
                254,160,88,174,204,22,114,15,42,51,71,75,19,135,16>>,
              <<>>}}]},
 [{aesc_fsm_SUITE,init_per_group_,
      [{aecore_suite_utils,mine_blocks_until_txs_on_chain,5,
           [{file,
                "/home/builder/aeternity/apps/aecore/test/aecore_suite_utils.erl"},
            {line,329}]},
       {aesc_fsm_SUITE,wait_for_signed_transaction_in_block,3,
           [{file,
                "/home/builder/aeternity/apps/aechannel/test/aesc_fsm_SUITE.erl"},
            {line,3024}]},
       {aesc_fsm_SUITE,prep_account,2,
           [{file,
                "/home/builder/aeternity/apps/aechannel/test/aesc_fsm_SUITE.erl"},
            {line,2914}]},
       {aesc_fsm_SUITE,prep_responder,2,
           [{file,
                "/home/builder/aeternity/apps/aechannel/test/aesc_fsm_SUITE.erl"},
            {line,2905}]},
       {aesc_fsm_SUITE,init_per_group_,1,
           [{file,
                "/home/builder/aeternity/apps/aechannel/test/aesc_fsm_SUITE.erl"},
            {line,397}]},
       {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1755}]},
       {test_server,run_test_case_eval1,6,
           [{file,"test_server.erl"},{line,1350}]},
       {test_server,run_test_case_eval,9,
           [{file,"test_server.erl"},{line,1194}]}],
      [{file,"/home/builder/aeternity/apps/aechannel/test/aesc_fsm_SUITE.erl"},
       {line,407}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1755}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1350}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1194}]}]}
```

## Steps to Reproduce the Problem

Can't be reproduced reliably.

## Logs, error output, etc.

https://circleci.com/gh/aeternity/aeternity/94592

### PR DESCRIPTION
**Pull request by tolbrino**
Previously we could run into a race condition where additional blocks
were mined even though we didn't expect that to happen.

Fixes #2928
Fixes #2929
Fixes #2949

### CODE REVIEW

File: apps/aecore/test/aecore_suite_utils.erl [hunk 1]
```diff
@@ -1203,3 +1192,37 @@ get_key_hash_by_delta(Node, Delta) ->
     {ok, Header} = rpc(Node, aec_chain, get_key_header_by_height, [TopHeight - Delta]),
     {ok, Hash} = aec_headers:hash_header(Header),
     Hash.
+
+mine_safe_setup(Node, MiningRate, Opts, LoopFun) ->
+    ok = rpc:call(Node, application, set_env,
+                  [aecore, expected_mine_rate, MiningRate], 5000),
```
Comment (uwiger) [inline apps/aecore/test/aecore_suite_utils.erl]: Any particular reason why each timeout is individually hard-coded to `5000`?

File: apps/aecore/test/aecore_suite_utils.erl [hunk 2]
```diff
@@ -324,21 +308,27 @@ mine_blocks_until_txs_on_chain(Node, TxHashes, MiningRate, Max) ->
...
+    [key, micro] = [aec_blocks:type(B) || B <- Blocks],
+
+    case rpc:call(Node, aec_tx_pool, peek, [infinity]) of
+        {ok, []} ->
+            {ok, Blocks};
+        {ok, [_|_]} ->
+            %% So, Tx(s) is/are back in the mempool, this means (unless some Txs arrived
+            %% from thin air) that we had a micro-fork. Let's check what state we stopped in
+            {ok, NewBlocks} = mine_safe_setup(Node, expected_mine_rate(), #{}, Fun),
+            [key, micro] = [aec_blocks:type(B) || B <- NewBlocks],
```
Comment (uwiger) [inline apps/aecore/test/aecore_suite_utils.erl]: Why is `NewBlocks` expected to be a list of two blocks, one key block followed by a microblock?

File: apps/aecore/test/aecore_suite_utils.erl (hunk 1 above)
Comment (tolbrino) [reply apps/aecore/test/aecore_suite_utils.erl]: No, I just didn't mess with the previous setup in that regard. So there might be some reasoning which I don't know about.

File: apps/aecore/test/aecore_suite_utils.erl (hunk 2 above)
Comment (tolbrino) [reply apps/aecore/test/aecore_suite_utils.erl]: I just used the assertion from the previous setup which expects the transactions in the mempool to appear in a microblock next. If any other situation occurs the test will crash here which is what is expected.
