### PR TITLE
GH 2811 System test failures

### LINKED ISSUE #2811: ST failure: aest_db_SUITE, log_has_errors
## Expected Behavior

No error messages in log

## Actual Behavior

[Failed CI](https://circleci.com/gh/aeternity/aeternity/85704):

```
%%% aest_db_SUITE ==> fortuna_compatibility.leave_upgrade_reestablish.sc_leave_upgrade_reestablish_different_nodes_partial_upgrade: FAILED
%%% aest_db_SUITE ==> log_has_errors
```

### LINKED ISSUE #2812: ST failure: aest_channels_SUITE, timeout
## Expected Behavior

Not triggering the timeout

## Actual Behavior

[Failed CI](https://circleci.com/gh/aeternity/aeternity/85583):
```

%%% aest_channels_SUITE ==> test_simple_different_nodes_channel: FAILED
%%% aest_channels_SUITE ==> {{timeout,{messages,[{'DOWN',#Ref<0.2341270753.776732673.144730>,process,
                             <0.9737.0>,noproc},
                     {'DOWN',#Ref<0.2341270753.776732673.144731>,process,
                             <0.9737.0>,noproc},
                     {<0.9739.0>,websocket_event,channel,on_chain_tx,
                      #{<<"jsonrpc">> => <<"2.0">>,
                        <<"method">> => <<"channels.on_chain_tx">>,
                        <<"params">> =>
                            #{<<"channel_id">> =>
                                  <<"ch_2VrawkiQsNUuVS9qXid6N3UeUTMeEu6nfNKyTaVrWVytvzD7qK">>,
                              <<"data">> =>
                                  #{<<"info">> => <<"channel_changed">>,
                                    <<"tx">> =>
                                        <<"tx_+QEDCwH4hLhAfOHNs1Xe8vxil5Xnh1g9W37FiEpRf/E8TMwYcB9HxLwxZ+aZob7zaGQMH8qg1FYuENjO1x0Rz5+aamLAa2ftAbhAgiDobuYv2Rkm9csJl3bwHiBo2sA9TP0++tDJAW3odpFveL4BoQLpLOZhVA0aEZ/Bef5n4cpnIdrxPX72CEwJAbh5+Hc0AaEGxTb3qHbfgee9CAvFHHTI43pMGcXnCFymREnezjU8U8uhAbG1d7zTJ8s55V5sAmvWp0obNd5sBlDErlHvq3WeQVtmhQukO3QAAIYP1+jpeACgWmJvHMXkcgn2qs5zEyPQdrLgpwVYlCsLgFhyJj/sC5YDAQGcw5w=">>,
                                    <<"type">> => <<"channel_withdraw_tx">>}},
                        <<"version">> => 1}}]}},
 [{aehttp_ws_test_utils,wait_for_msg,5,
                        [{file,"/home/circleci/aeternity/_build/system_test+test/extras/apps/aehttp/test/aehttp_ws_test_utils.erl"},
                         {line,313}]},
  {aest_api,sc_wait_for_channel_event,2,
            [{file,"/home/circleci/aeternity/_build/system_test+test/extras/system_test/common/helpers/aest_api.erl"},
             {line,253}]},
  {aest_api,sc_process_offchain_tx,4,
            [{file,"/home/circleci/aeternity/_build/system_test+test/extras/system_test/common/helpers/aest_api.erl"},
             {line,301}]},
  {aest_api,sc_transfer,7,
            [{file,"/home/circleci/aeternity/_build/system_test+test/extras/system_test/common/helpers/aest_api.erl"},
             {line,296}]},
  {aest_channels_SUITE,'-test_offchain_operations/2-fun-0-',1,
                       [{file,"/home/circleci/aeternity/_build/system_test+test/extras/system_test/common/aest_channels_SUITE.erl"},
                        {line,390}]},
  {aest_channels_SUITE,'-test_offchain_operations/2-lc$^1/1-0-',2,
                       [{file,"/home/circleci/aeternity/_build/system_test+test/extras/system_test/common/aest_channels_SUITE.erl"},
                        {line,392}]},
  {aest_channels_SUITE,test_offchain_operations,2,
                       [{file,"/home/circleci/aeternity/_build/system_test+test/extras/system_test/common/aest_channels_SUITE.erl"},
                        {line,392}]},
  {aest_channels_SUITE,simple_channel_test,4,
                       [{file,"/home/circleci/aeternity/_build/system_test+test/extras/system_test/common/aest_channels_SUITE.erl"},
                        {line,209}]}]}
```

### LINKED ISSUE #2813: ST failure: aest_channels_SUITE , badmatch,{ok,#{<<"info">> => <<"channel_changed">>
## Expected Behavior

Receiving the expected close mutual tx

## Actual Behavior

Receiving an unexpected withdrawal transaction. [Failed CI](https://circleci.com/gh/aeternity/aeternity/85556):
```

%%% aest_channels_SUITE ==> test_simple_same_node_channel: FAILED
%%% aest_channels_SUITE ==> {{badmatch,{ok,#{<<"info">> => <<"channel_changed">>,
                 <<"tx">> =>
                     <<"tx_+QEDCwH4hLhAYBj2C1P6pUsA6F9JsXf4AvseeWtc5o6ehUM/RRJ2plrG/ZKN+QC3lPK6OPZchu2mvk3GgDOqDM9Fro9qrizrDrhAdCvx9a+1zCOxPJ4ocuLjOv/q4bLBBZDUZPDw9UyelCOE6jTlhwCugo1f5e4zAUKzEiFGy6ipjJEPsqqbeMoSArh5+Hc0AaEGxTb3qHbfgee9CAvFHHTI43pMGcXnCFymREnezjU8U8uhAbG1d7zTJ8s55V5sAmvWp0obNd5sBlDErlHvq3WeQVtmhQukO3QAAIYP1+jpeACg+qkbkYbUeot8Zo8Suvb99JpHnLuu37++QJ5oUGv+f50DAQjjCrs=">>,
                 <<"type">> => <<"channel_withdraw_tx">>}}},
 [{aest_api,sc_close_mutual,2,
            [{file,"/home/circleci/aeternity/_build/system_test+test/extras/system_test/common/helpers/aest_api.erl"},
             {line,165}]},
  {aest_channels_SUITE,simple_channel_test,4,
                       [{file,"/home/circleci/aeternity/_build/system_test+test/extras/system_test/common/aest_channels_SUITE.erl"},
                        {line,212}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1539}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1055}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,987}]}]}
```

### PR DESCRIPTION
**Pull request by velzevur**
This PR improves `aesc_txs_SUITE` with corresponding checks that deposits and withdrawals can not be included on-chain after the channel had either entered a closing state or is already closed.

This PR improves system tests and fixes #2813, fixes #2812 and fixes #2811. It also fixes an unreported yet issue with a client receiving `peer_disconnected` while disconnecting.

### CODE REVIEW

File: system_test/common/aest_channels_SUITE.erl [hunk 1]
```diff
@@ -292,8 +293,8 @@ reestablish_state_channel_perform_operations_close({INodeName, RNodeName},
     wait_for_value({txs_on_chain, [CloseTxHash]}, NodeNames, 5000, Config),
     %% wait for min depth to be reached so the channels die
     #{height := TopHeight} = aest_nodes:get_top(INodeName),
-    KeyBlocksToMine = 4 + 2, % min depth is 4
-    wait_for_value({height, TopHeight + KeyBlocksToMine}, NodeNames, 10000, Config),
+    KeyBlocksToMine = ?MIN_DEPTH + 2, % min depth is 4
+    wait_for_value({height, TopHeight + KeyBlocksToMine}, NodeNames, 20000, Config),
```
Comment (hanssv) [inline system_test/common/aest_channels_SUITE.erl]: So instead of waiting 10 seconds we wait 20 seconds? This is a very, very, very long time?!

File: system_test/common/aest_channels_SUITE.erl [hunk 2]
```diff
@@ -292,8 +293,8 @@ reestablish_state_channel_perform_operations_close({INodeName, RNodeName},
     wait_for_value({txs_on_chain, [CloseTxHash]}, NodeNames, 5000, Config),
     %% wait for min depth to be reached so the channels die
     #{height := TopHeight} = aest_nodes:get_top(INodeName),
-    KeyBlocksToMine = 4 + 2, % min depth is 4
-    wait_for_value({height, TopHeight + KeyBlocksToMine}, NodeNames, 10000, Config),
+    KeyBlocksToMine = ?MIN_DEPTH + 2, % min depth is 4
```
Comment (hanssv) [inline system_test/common/aest_channels_SUITE.erl]: So mining 13 blocks instead of 6? that makes the test slower, can it be avoided?

Comment (velzevur) [reply system_test/common/aest_channels_SUITE.erl]: Returned old value

File: system_test/common/aest_channels_SUITE.erl (hunk 1 above)
Comment (velzevur) [reply system_test/common/aest_channels_SUITE.erl]: Fixed

File: system_test/common/aest_channels_SUITE.erl (hunk 2 above)
Comment (tolbrino) [reply system_test/common/aest_channels_SUITE.erl]: Since we verify that the min depth strategy works fine with other values, we could use a factor of `0` here and in general in other tests, which would require only a single block.
