### PR TITLE
Fix issue in aec_chain_state

### LINKED ISSUE #3311: When syncing from backup, accept previous states in DB if they don't differ
After unzipping DB from https://downloads.aeternity.io

and starting node, there are errors during sync: `found_already_calculated_state`

Coming from: aec_chain_state:update_state_tree/4

If the states are identical, we should ignore this error.

### PR DESCRIPTION
**Pull request by velzevur**
The service download.aeternity.io is fed some database snapshots. Those are
produced by simply grabbing mnesia files and publishing them. If at the moment
of moving the data a block was in the process of being consumed by the node
itself, there is a risk of a race condition: the block (wrapped as a MPT node)
is being included in the DB while it is not yet set to be the top block. This
PR identifies if a node's hash is already known and if so - checks if it
produces the same expected result. If so - it is accepted. In the case of a DB
node being found with the same hash but different state trees - the node is
still crashing, no change there.

While working on the PR, 2 small bugs were identified and fixed, please
consult the comments below.

Fixes #3311

The work on this PR is supported by the Aeternity Crypto Foundation.

### CODE REVIEW

File: apps/aecore/src/aec_chain_state.erl [hunk 1]
```diff
@@ -972,7 +987,7 @@ update_fraud_info(ForkInfoIn, Node, State) ->
 
 handle_top_block_change(OldTopHash, NewTopDifficulty, Node, Events, State) ->
     case get_top_block_hash(State) of
-        OldTopHash -> State;
+        OldTopHash -> {State, []};
```
Comment (velzevur) [inline apps/aecore/src/aec_chain_state.erl:990]: Small bug: the function returns a tuple of a new state and events. If the change had not changed, no new events.

This module would surely benefit from some `-spec`-s

File: apps/aecore/src/aec_db.erl [hunk 2]
```diff
@@ -734,7 +734,7 @@ find_signal_count(Hash) ->
 add_tx_location(STxHash, BlockHash) when is_binary(STxHash),
                                          is_binary(BlockHash) ->
     ?t(mnesia:write(#aec_tx_location{key = STxHash, value = BlockHash}),
-       [aec_tx_location, STxHash]).
+       [{aec_tx_location, STxHash}]).
```
Comment (velzevur) [inline apps/aecore/src/aec_db.erl:737]: Possibly a typo.

File: apps/aecore/test/aec_chain_state_tests.erl [hunk 3]
```diff
@@ -487,3 +487,45 @@ make_spend_tx(Sender, SenderNonce, Recipient, Fee, Amount) ->
...
+     ]}.
+
+accept_existing_db_node() ->
+    [B1, B2, B3] = prep_micro_blocks(3),
+    {ok, _} = ?TEST_MODULE:insert_block(B1),
+    {ok, _} = ?TEST_MODULE:insert_block(B2),
+    Node = ?TEST_MODULE:wrap_block(B3),
+    Ctx = ?TEST_MODULE:build_insertion_ctx(Node, micro, undefined),
+    {ok, _} = ?TEST_MODULE:insert_block(B3),
+    ?TEST_MODULE:internal_insert_transaction(Node, B3, undefined, Ctx),
```
Comment (velzevur) [inline apps/aecore/test/aec_chain_state_tests.erl:529]: This goes around the dirty check if the node is present in the DB. In normal cases those requests are serialised by the `aec_conductor` process so the dirty read shall be sufficient.

File: apps/aecore/src/aec_chain_state.erl (hunk 1 above)
Comment (gorbak25) [inline apps/aecore/src/aec_chain_state.erl:990]:
```suggestion
        OldTopHash -> {State, no_events()};
```

**Review by gorbak25 — DISMISSED** [review]

**Review by uwiger — APPROVED** [review]

**Review by gorbak25 — APPROVED** [review]
