### PR TITLE
Fix discriminator in user API re oracle response transaction

### LINKED ISSUE #2564: OracleRespondTx  Vs  OracleResponseTx
## Expected Behavior

The transaction type should be `OracleRespondTx `

## Actual Behavior

The transaction type is `OracleResponseTx `

## Steps to Reproduce the Problem

transaction link: https://sdk-mainnet.aepps.com/v2/transactions/th_apTWfWu6RPLyritqib2mnKWc5Hcaw6uVkQC68jKfUq2t2mStS

## Related Links

swagger api: https://sdk-mainnet.aepps.com/api

protocol: https://github.com/aeternity/protocol/search?q=OracleRespondTx&unscoped_q=OracleRespondTx

### PR DESCRIPTION
**Pull request by lucafavatella**
Delivers https://www.pivotaltracker.com/story/show/167193244
Fixes #2564

### CODE REVIEW

File: apps/aehttp/test/aehttp_discriminator_SUITE.erl [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+        , oracle_response_tx
+        , name_preclaim_tx
+        , name_claim_tx
+        , name_transfer_tx
+        , name_update_tx
+        , name_revoke_tx
+        , contract_call_tx
+        , contract_create_tx
+        %% TODO , ga_attach_tx
+        %% TODO , ga_meta_tx
```
Comment (lucafavatella) [inline apps/aehttp/test/aehttp_discriminator_SUITE.erl]: These two TODOs are tracked as https://www.pivotaltracker.com/story/show/167198984
