### PR TITLE
Fix race

### LINKED ISSUE #2869: CT failure aesc_fsm_SUITE ==> {timeout,..
## Expected Behavior
tests passing

## Actual Behavior
```
%%% aesc_fsm_SUITE ==> {timeout,[{aesc_fsm_SUITE,await_channel_changed_report,2,
                          [{file,"/home/builder/aeternity/apps/aechannel/test/aesc_fsm_SUITE.erl"},
                           {line,2621}]},
          {aesc_fsm_SUITE,create_channel_from_spec,7,
                          [{file,"/home/builder/aeternity/apps/aechannel/test/aesc_fsm_SUITE.erl"},
                           {line,2278}]},
          {aesc_fsm_SUITE,check_incorrect_deposit,1,
                          [{file,"/home/builder/aeternity/apps/aechannel/test/aesc_fsm_SUITE.erl"},
                           {line,1392}]},
          {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1546}]},
          {test_server,run_test_case_eval1,6,
                       [{file,"test_server.erl"},{line,1062}]},
          {test_server,run_test_case_eval,9,
                       [{file,"test_server.erl"},{line,994}]}]}
```
[CI log](https://circleci.com/gh/aeternity/aeternity/89000)

### PR DESCRIPTION
**Pull request by velzevur**
Fixes #2869

### CODE REVIEW

**Comment by velzevur** [comment]
`test_roma` failed with #2869, restarting it

File: apps/aechannel/src/aesc_fsm.erl [hunk 1]
```diff
@@ -710,14 +710,16 @@ awaiting_signature(cast, {?SIGNED, ?FND_CREATED, SignedTx} = Msg,
...
+            D0 = D#data{ create_tx = SignedTx
+                       , op = #op_ack{ tag = ?FND_CREATED
+                                     , data = OpData}
+                       , client_may_disconnect = true },
+            %% start the watcher before sending the transaction to the other
+            %% participant
+            {ok, D1} = start_chain_watcher({?MIN_DEPTH, ?WATCH_FND}, SignedTx,
+                                           Updates, D0),
+            D2 = send_funding_signed_msg(SignedTx, log(rcv, ?SIGNED, Msg, D1)),
             report_on_chain_tx(?FND_CREATED, SignedTx, D1),
```
Comment (uwiger) [inline apps/aechannel/src/aesc_fsm.erl]:
```suggestion
             report_on_chain_tx(?FND_CREATED, SignedTx, D2),
```
