### PR TITLE
Fix transaction API etag response header

### LINKED ISSUE #3622: cache invalidation for transaction endpoint doesn't seem to work as expected
sending the same request over and over doesn't invalidate the cache as would be expected, see attached video

https://www.youtube.com/watch?v=K94G3AcxCNc

### PR DESCRIPTION
**Pull request by dincho**
fixes #3622

### CODE REVIEW

File: apps/aehttp/src/aehttp_cache_etag.erl [hunk 1]
```diff
@@ -157,6 +170,19 @@ etag_generation_hash(Hash) ->
             undefined
     end.
 
+-spec etag_transaction_hash(binary()) -> {ok, binary()} | undefined.
+etag_transaction_hash(Hash) ->
+    case aec_chain:find_tx_with_location(Hash) of
+        {mempool, _Tx} ->
+            {ok, aeu_hex:bin_to_hex(Hash)};
+        {BlockHash, _Tx} when is_binary(BlockHash) ->
```
Comment (hanssv) [inline apps/aehttp/src/aehttp_cache_etag.erl:178]: What about micro-forks (or forks...)

**Review by hanssv — DISMISSED** [review]

File: apps/aehttp/src/aehttp_cache_etag.erl (hunk 1 above)
Comment (hanssv) [reply apps/aehttp/src/aehttp_cache_etag.erl:178]: Nah, that is fine

**Review by velzevur — DISMISSED** [review]

**Review by hanssv — APPROVED** [review]

**Review by velzevur — APPROVED** [review]
