### PR TITLE
Fix OAS3 issues

### LINKED ISSUE #3539: "consumes" is not defined in names endpoints in Swagger 2
- /debug/names/claim
- /debug/names/preclaim
- /debug/names/transfer
- /debug/names/revoke
- /debug/names/update 

I assume it should be
```json
        "consumes": [
          "application/json"
        ],
```
as in other endpoints. The lack of this hint breaks the default behavior of `swagger-client`.

### PR DESCRIPTION
**Pull request by velzevur**
This fixes #3539 

While the initial bug report was regarding missing `consumes` section and in `OAS3` [specification](https://swagger.io/specification/) there is no such keyword (there is in `swagger 2`, the old version) - there was an unrelated bug. Addressed in this PR and now JS client can easily be built by:

```
$ curl -X POST \
  https://generator3.swagger.io/api/generate \
  -H 'content-type: application/json' \
  -d '{
  "specURL" : "https://raw.githubusercontent.com/aeternity/aeternity/09e3aa7348f17b66e92719d781345b16199ebd8a/apps/aehttp/priv/oas3.yaml",
  "lang" : "javascript",
  "type" : "CLIENT",
  "codegenVersion" : "V3"
}' -o js.zip
```

@davidyuk please confirm this resolves the issue on your end.

### CODE REVIEW

File: apps/aehttp/src/aehttp_api_validate.erl [hunk 1]
```diff
@@ -192,6 +201,7 @@ prepare_param_({"type", "float"}, Value, Name, _, _) ->
 prepare_param_({"type", "integer"}, Value, Name, _, _) ->
     try {ok, to_int(Value)}
     catch
+        error:function_clause  -> 1 = {domat, Name, Value};
```
Comment (gorbak25) [inline apps/aehttp/src/aehttp_api_validate.erl:204]: wut? This will never match

Comment (velzevur) [reply apps/aehttp/src/aehttp_api_validate.erl]: oops, one of my debug messages leaked out :D

**Review by gorbak25 — DISMISSED** [review]

File: apps/aehttp/src/aehttp_api_validate.erl [hunk 2]
```diff
@@ -127,13 +127,24 @@ populate_param(Param, Req, Validator, EndpointsMod) ->
     Name = proplists:get_value("name", Param),
     case get_param_value(In, Name, Req) of
         {ok, Value, Req1} ->
-            case prepare_param(Param, Value, Name, Validator, EndpointsMod) of
+            case prepare_param(params_priority(Param), Value, Name, Validator, EndpointsMod) of
```
Comment (velzevur) [inline apps/aehttp/src/aehttp_api_validate.erl:130]: It is an implicit requirement that `default` goes first as otherwise it gets ignored :)

**Comment by davidyuk** [comment]
I have built this PR locally (`node_revision: "09e3aa7348f17b66e92719d781345b16199ebd8a" `) and as I see, this does not resolve the issue on my end:  `consumes` still is not present in the definitions of names endpoints in Swagger 2 definition (`/v2/api`).

**Comment by velzevur** [comment]
@davidyuk why do you use `/v2/`? This is the old `swagger2` API, you should build the SDK against the new `/v3` one instead.

**Comment by davidyuk** [comment]
Well, I'm doing my work step by step and noticed the inconsistency in the old swagger definitions, my issue was about that. It is not a blocker for me, I have a workaround. But fixing this may improve compatibility with other tools. In the end, I will use the latest definitions (v3), but I can't confirm that this PR fixes the issue I reported (#3539).

**Review by uwiger — APPROVED** [review]

**Comment by velzevur** [comment]
@davidyuk Is this working for you?

**Comment by davidyuk** [comment]
> @davidyuk Is this working for you?

I have checked, it works. Thank you!

**Review by gorbak25 — APPROVED** [review]
